-- ====================================================================
-- ProdGuard AI - Supabase Database Schema
-- Run this script in Supabase Dashboard -> SQL Editor -> Run
-- ====================================================================

-- 1. Create Prediction History Table
CREATE TABLE IF NOT EXISTS public.prediction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    time TEXT,
    date TEXT,
    machine_type TEXT DEFAULT 'M',
    risk_score NUMERIC,
    risk_level TEXT,
    priority_score NUMERIC,
    machine_failure_probability NUMERIC,
    input_data JSONB DEFAULT '{}'::jsonb
);

-- 2. Create Workflow Incidents Table
CREATE TABLE IF NOT EXISTS public.workflow_incidents (
    incident_id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    current_stage TEXT NOT NULL DEFAULT 'DETECTED',
    assigned_team TEXT DEFAULT 'Maintenance Team',
    notes TEXT DEFAULT '',
    escalated BOOLEAN DEFAULT FALSE,
    last_updated TEXT
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.prediction_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workflow_incidents ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies allowing Public / Anon read and write (for Hackathon prototype)
CREATE POLICY "Allow public read prediction_history"
ON public.prediction_history FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow public insert prediction_history"
ON public.prediction_history FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Allow public delete prediction_history"
ON public.prediction_history FOR DELETE
TO anon, authenticated
USING (true);

CREATE POLICY "Allow public all workflow_incidents"
ON public.workflow_incidents FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 5. Insert initial default incident record
INSERT INTO public.workflow_incidents (incident_id, current_stage, assigned_team, notes, escalated, last_updated)
VALUES ('INC-1042', 'DETECTED', 'Maintenance Team', 'System initialized for continuous telemetry monitoring.', false, '10:00 AM')
ON CONFLICT (incident_id) DO NOTHING;
